service: serverless-next

provider:
  name: aws
  runtime: nodejs16.x
  region: eu-west-1
  httpApi:
    cors: true

functions:
  api:
    handler: server.handler
    memorySize: 2048
    events:
      - httpApi: ANY /
      - httpApi: ANY /{proxy+}

plugins:
  - serverless-esbuild

package:
  patterns:
    - ".next"
    - "node_modules"
    - "public"
    - "_next"
    - "next.config.js"
    - "next-i18next.config.js"
    - "package.json"

custom:
  esbuild:
    bundle: true
    minify: true
    exclude: "*"
    external:
      - "next"